### ISSUE TITLE
validation using html5

### ISSUE THREAD

**Issue by iamsahilvhora** [jackrugile/placeholdem#10]
There is a issue when we do the validation using html5 'required' attribute. It validate the text-box for email because it is having the type="email", but for simple type="text" it is considering the placeholder value as it's actual value. Please check it once.

**Comment by jackrugile** [comment]
Will be looking into this issue soon. Looks like it's related to #14 as well.

**Comment by jackrugile** [comment]
Just wanted to give a heads up that this plugin is officially inactive. I've updated the readme to reflect that. Thanks for using the plugin and I apologize for any inconvenience.

> This project is no longer being developed or maintained. The effect this plugin gives is visually appealing, but it's a bad practice in terms of usability and accessibility. On top of that, manipulating the values of different HTML5 input types directly has a lot of issues (text, email, number, search, etc.). I suggest using an alternative styling for labels and placeholders, such as Floating Labels.
