### ISSUE TITLE
ng-model and placeholdem

### ISSUE THREAD

**Issue by dobiedad** [jackrugile/placeholdem#11]
when using ng-model on the form tags placeholdem works in reverse. the placeholder is not visible but once you focus into another input area the place holder in the previous input  animation starts from 0 letters and then animates to the word.

**Comment by jackrugile** [comment]
@leomdivani Hey, I am not very familiar with Angular and how it handles inputs. Would you be able to put together a stripped down demo of the issue so I can look into it further?

**Comment by umpirsky** [comment]
Same happens to me on http://stajesti.rs. No placeholder on search field, once you give it focus, it works.

Code: https://github.com/umpirsky/stajesti.rs/blob/master/app/scripts/controllers/main.js#L8

When I move this line to https://github.com/umpirsky/stajesti.rs/blob/master/app/scripts/app.js it works, but that feels wrong, isn't it?
