### ISSUE TITLE
doesn't restore placeholder after reset form

### ISSUE THREAD

**Issue by nicolag** [jackrugile/placeholdem#12]
Hey Jack,

I love the placeholdem but there is an issue, after reset/clear the form it doesn't restore the original placeholder value unless you click on it and turn blur again. Would you mind improving this? Look forward to the solution. Thx.

Nicole

**Comment by jackrugile** [comment]
Thank you for bringing this to my attention. Please try v1.0.2 and let me know if you run into any issues.

**Comment by nicolag** [comment]
awesome, awesome, it works great!
