### ISSUE TITLE
Required field validation doesn't work

### ISSUE THREAD

**Issue by himanpatel** [jackrugile/placeholdem#14]
i am using it in my project and if i remove your js  validation works perfectly and if i add it then my required field validation stopped working.

**Comment by makeev** [comment]
What version of django? Any errors in JS console?

**Comment by himanpatel** [comment]
v1.0.2
No Js Error on console

**Comment by jerichozis** [comment]
The problem of whole plugin is that it use value as a placeholder. And its completely crash ever validation atempt.So,i figured out solution.
1 - Go to plugin js file
2 - Replace all "value" with "placeholder"
3 - Profit! Now it works as a placeholder.

And a little comment to developer:
Im using your plugin with fairly popular "validate.js" plugin. And i had perform this trick to make this plugin work with your.Can you add some custom option to placeholdem to use it like a ,strictly speaking, placeholder.

**Comment by jackrugile** [comment]
Hey, thanks for bringing this to my attention you guys. I apologize for the delay on updates. I'll try to take a look at this soon, give it some tests, and get it implemented.

**Comment by jackrugile** [comment]
Just wanted to give a heads up that this plugin is officially inactive. I've updated the readme to reflect that. Thanks for using the plugin and I apologize for any inconvenience.

> This project is no longer being developed or maintained. The effect this plugin gives is visually appealing, but it's a bad practice in terms of usability and accessibility. On top of that, manipulating the values of different HTML5 input types directly has a lot of issues (text, email, number, search, etc.). I suggest using an alternative styling for labels and placeholders, such as Floating Labels.
