### ISSUE TITLE
placeholdem.js - delay and animation time

### ISSUE THREAD

**Issue by crisc2000** [jackrugile/placeholdem#15]
hello.
it's possible to set a delay for running the animation (after event) and a animation time ?

for example if I want that animation to start only 1 second after i click (focus) the input box , and the animation to be more slower.

**Comment by jackrugile** [comment]
There isn't currently a way to do what you requested, but I can look into it. I'm open to pull requests also if you're interested in contributing.

**Comment by jackrugile** [comment]
Just wanted to give a heads up that this plugin is officially inactive. I've updated the readme to reflect that. Thanks for using the plugin and I apologize for any inconvenience.

> This project is no longer being developed or maintained. The effect this plugin gives is visually appealing, but it's a bad practice in terms of usability and accessibility. On top of that, manipulating the values of different HTML5 input types directly has a lot of issues (text, email, number, search, etc.). I suggest using an alternative styling for labels and placeholders, such as Floating Labels.
