### ISSUE TITLE
placeholdem - colour of placeholder text

### ISSUE THREAD

**Issue by ramasaig** [jackrugile/placeholdem#16]
Placeholdem seems to over-ride the browser default colour/opacity of the placeholder text. There are ways to style placeholder text, but they vary between browsers and are therefore tedious to apply.
Would it be possible to include some default (or even editable) styling in 'placeholdem'?

**Comment by jackrugile** [comment]
Just wanted to give a heads up that this plugin is officially inactive. I've updated the readme to reflect that. Thanks for using the plugin and I apologize for any inconvenience.

> This project is no longer being developed or maintained. The effect this plugin gives is visually appealing, but it's a bad practice in terms of usability and accessibility. On top of that, manipulating the values of different HTML5 input types directly has a lot of issues (text, email, number, search, etc.). I suggest using an alternative styling for labels and placeholders, such as Floating Labels.
