### ISSUE TITLE
messages are not stop after clicked on email field

### ISSUE THREAD

**Issue by agusmakmun** [jackrugile/placeholdem#17]
Hello there, i found this problem when i looking for console on my browser after clicked the email field. this message are not stop.

![placeholdem](https://cloud.githubusercontent.com/assets/7134451/17200984/405cf702-54b4-11e6-9013-e18d411b424c.png)

**Comment by jackrugile** [comment]
Just wanted to give a heads up that this plugin is officially inactive. I've updated the readme to reflect that. Thanks for using the plugin and I apologize for any inconvenience.

> This project is no longer being developed or maintained. The effect this plugin gives is visually appealing, but it's a bad practice in terms of usability and accessibility. On top of that, manipulating the values of different HTML5 input types directly has a lot of issues (text, email, number, search, etc.). I suggest using an alternative styling for labels and placeholders, such as Floating Labels.
