### ISSUE TITLE
Wordpress implementation

### ISSUE THREAD

**Issue by LeBaux** [jackrugile/placeholdem#6]
I know this is probably a stupid question for github, but how can one add this to wordpress theme?

If this question is way too stupid just close it.
In any case, thanks for this js!

**Comment by jackrugile** [comment]
Hey, not a stupid question.

Do you have a main JS file that is part of your WordPress theme? If so, you could include both the Placeholdem plugin and call to the plugin in there. If your theme doesn't currently include any custom JS, you will have to make a file and then include it in your theme's header or footer, or to do it properly, register the script in your functions.php file. Hopefully that gets you on the right track. Let me know if you need any more assistance.
