### ISSUE TITLE
Incorrent work with input type=email and password

### ISSUE THREAD

**Issue by Rad1calDreamer** [jackrugile/placeholdem#8]
Hi,
Found little wrong plugin's work with input[type=email] and input[type=password]
Here is an example http://jsfiddle.net/bBLE8/

**Comment by jackrugile** [comment]
Hey, can you double check that link? I think it is the wrong one because I just see a button.

**Comment by Rad1calDreamer** [comment]
sorry, isert correct link

**Comment by jackrugile** [comment]
Ah ok, that is interesting bug with the email field. Just to clarify, this what I am seeing, let me know if you see the same:
1. Email - On blur, the refill of the field only fills "some", not "some email" as it is supposed to.
2. Password - This is technically behaving as it should, but you'd rather it show "some password", and then show the password dots when the user actually starts typing.

I will look into the email input for sure, as that should not be happening. As for the password field, that is a tricky one. That is inherently how password fields work, so you might need to do some trickery where you swap the "type" of the input on focus and on blur. I will think about that one.

Thanks for pointing this out, let me know if I am understanding correctly.

**Comment by Rad1calDreamer** [comment]
you understand all right.
 thank you for such a quick response!

**Comment by jackrugile** [comment]
My initial debugging session yielded no useful results. Will need some more time to look into this. Thanks for the heads up on this.

**Comment by hamburger123456** [comment]
hey is there any solution in the nearest future. It's a great effect would like to use it.

**Comment by jackrugile** [comment]
Hey hamburger123456, so sorry for the delay on this. It is such a strange issue and I am having trouble debugging it. I apologize for the inconvenience, I hope I can work this out soon.

**Comment by jackrugile** [comment]
Just wanted to give a heads up that this plugin is officially inactive. I've updated the readme to reflect that. Thanks for using the plugin and I apologize for any inconvenience.

> This project is no longer being developed or maintained. The effect this plugin gives is visually appealing, but it's a bad practice in terms of usability and accessibility. On top of that, manipulating the values of different HTML5 input types directly has a lot of issues (text, email, number, search, etc.). I suggest using an alternative styling for labels and placeholders, such as Floating Labels.
